apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dpp-dev
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: dpp-api
  - patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 1
    target:
      kind: PodDisruptionBudget
      name: dpp-api-pdb
