#!/usr/bin/env python3
"""
Seed demo data into the production API and test all endpoints.

Reads the demo JSON files generated by generate_demo_data.py, then:
  1. Seeds products into Neo4j via the sector API
  2. Creates battery passports via the battery API
  3. Tests compliance, ML, lifecycle, supply-chain, and audit endpoints
  4. Produces a test report

Usage:
  python scripts/seed_and_test_demo.py                     # default: http://51.77.144.54:8100
  API_URL=http://localhost:8000 python scripts/seed_and_test_demo.py  # local
"""
import json
import os
import sys
import time
from pathlib import Path

try:
    import requests
except ImportError:
    print("pip install requests")
    sys.exit(1)

API_URL = os.environ.get("API_URL", "http://51.77.144.54:8100")
DEMO_DIR = Path(__file__).resolve().parent.parent / "data" / "demo"

AUTH_USER = os.environ.get("AUTH_USER", "operator@example.com")
AUTH_PASS = os.environ.get("AUTH_PASS", "demo-password")

results: list[dict] = []


def load_json(name: str):
    p = DEMO_DIR / name
    if not p.exists():
        print(f"  MISSING: {p} — run generate_demo_data.py first")
        return []
    with open(p) as f:
        return json.load(f)


def get_token() -> str | None:
    try:
        r = requests.post(
            f"{API_URL}/api/v1/auth/token",
            data={"username": AUTH_USER, "password": AUTH_PASS},
            timeout=10,
        )
        if r.status_code == 200:
            return r.json().get("access_token")
    except Exception:
        pass
    return None


def headers(token: str | None) -> dict:
    h = {"Content-Type": "application/json"}
    if token:
        h["Authorization"] = f"Bearer {token}"
    return h


def record(name: str, method: str, url: str, status: int, ok: bool, detail: str = ""):
    results.append({
        "test": name, "method": method, "url": url,
        "status": status, "ok": ok, "detail": detail[:200],
    })
    icon = "PASS" if ok else "FAIL"
    print(f"    [{icon}] {method} {url} → {status} {detail[:80]}")


def test_health(token):
    print("\n  1. HEALTH CHECKS")
    for path in ["/health", "/ready"]:
        try:
            r = requests.get(f"{API_URL}{path}", timeout=10)
            record(f"health:{path}", "GET", path, r.status_code,
                   r.status_code == 200, r.text[:100])
        except Exception as e:
            record(f"health:{path}", "GET", path, 0, False, str(e))


def test_dpp_sectors(token):
    print("\n  2. DPP SECTORS LIST")
    try:
        r = requests.get(f"{API_URL}/api/v1/dpp", headers=headers(token), timeout=10)
        record("dpp:sectors", "GET", "/api/v1/dpp", r.status_code,
               r.status_code == 200, r.text[:100])
    except Exception as e:
        record("dpp:sectors", "GET", "/api/v1/dpp", 0, False, str(e))


def seed_dpp_products(token):
    print("\n  3. SEED DPP PRODUCTS (sector API)")
    dpp_requests = load_json("demo_dpp_create_requests.json")
    ok_count = 0
    for i, req in enumerate(dpp_requests):
        try:
            r = requests.post(
                f"{API_URL}/api/v1/dpp/sector",
                headers=headers(token),
                json=req,
                timeout=30,
            )
            ok = r.status_code in (200, 201, 409)
            if ok:
                ok_count += 1
            record(f"seed:dpp:{i}", "POST", "/api/v1/dpp/sector",
                   r.status_code, ok,
                   f"{req['sector']}/{req['gtin']} → {r.text[:60]}")
        except Exception as e:
            record(f"seed:dpp:{i}", "POST", "/api/v1/dpp/sector", 0, False, str(e))
    print(f"    → {ok_count}/{len(dpp_requests)} products seeded")
    return dpp_requests


def test_dpp_get(token, dpp_requests):
    print("\n  4. GET DPP PRODUCTS")
    for req in dpp_requests[:5]:
        sector = req["sector"]
        gtin = req["gtin"]
        serial = req["serial_number"]
        path = f"/api/v1/dpp/sector/{sector}/{gtin}/{serial}"
        try:
            r = requests.get(f"{API_URL}{path}", headers=headers(token), timeout=10)
            record(f"get:dpp:{sector}", "GET", path, r.status_code,
                   r.status_code == 200, r.text[:80])
        except Exception as e:
            record(f"get:dpp:{sector}", "GET", path, 0, False, str(e))


def test_dpp_list_by_sector(token):
    print("\n  5. LIST DPPs BY SECTOR")
    for sector in ["electronics", "batteries", "textiles"]:
        path = f"/api/v1/dpp/sector/{sector}?limit=5"
        try:
            r = requests.get(f"{API_URL}{path}", headers=headers(token), timeout=10)
            record(f"list:sector:{sector}", "GET", path, r.status_code,
                   r.status_code == 200, r.text[:80])
        except Exception as e:
            record(f"list:sector:{sector}", "GET", path, 0, False, str(e))


def seed_batteries(token):
    print("\n  6. SEED BATTERY PASSPORTS")
    payloads = load_json("demo_battery_payloads.json")
    ok_count = 0
    for i, bp in enumerate(payloads):
        try:
            r = requests.post(
                f"{API_URL}/api/v1/dpp/battery",
                headers=headers(token),
                json=bp,
                timeout=30,
            )
            ok = r.status_code in (200, 201, 409)
            if ok:
                ok_count += 1
            record(f"seed:battery:{i}", "POST", "/api/v1/dpp/battery",
                   r.status_code, ok,
                   f"{bp['gtin']}/{bp['serial_number']} → {r.text[:60]}")
        except Exception as e:
            record(f"seed:battery:{i}", "POST", "/api/v1/dpp/battery", 0, False, str(e))
    print(f"    → {ok_count}/{len(payloads)} batteries seeded")
    return payloads


def test_battery_get(token, payloads):
    print("\n  7. GET BATTERY PASSPORTS")
    for bp in payloads[:3]:
        path = f"/api/v1/dpp/battery/{bp['gtin']}/{bp['serial_number']}"
        try:
            r = requests.get(f"{API_URL}{path}", headers=headers(token), timeout=10)
            record(f"get:battery:{bp['gtin'][:8]}", "GET", path,
                   r.status_code, r.status_code == 200, r.text[:80])
        except Exception as e:
            record(f"get:battery:{bp['gtin'][:8]}", "GET", path, 0, False, str(e))


def test_supply_chain(token, dpp_requests):
    print("\n  8. SUPPLY CHAIN TRACE")
    for req in dpp_requests[:3]:
        gtin = req["gtin"]
        path = f"/api/v1/dpp/sector/supply-chain/{gtin}"
        try:
            r = requests.get(f"{API_URL}{path}", headers=headers(token), timeout=10)
            record(f"supply-chain:{gtin[:8]}", "GET", path,
                   r.status_code, r.status_code == 200, r.text[:80])
        except Exception as e:
            record(f"supply-chain:{gtin[:8]}", "GET", path, 0, False, str(e))


def test_qr_carrier(token, dpp_requests):
    print("\n  9. QR / CARRIER")
    if dpp_requests:
        req = dpp_requests[0]
        gtin, serial = req["gtin"], req["serial_number"]
        path = f"/api/v1/dpp/{gtin}/{serial}/carrier"
        try:
            r = requests.get(f"{API_URL}{path}", headers=headers(token), timeout=10)
            record("carrier:info", "GET", path, r.status_code,
                   r.status_code == 200, r.text[:80])
        except Exception as e:
            record("carrier:info", "GET", path, 0, False, str(e))

        path_qr = f"/api/v1/dpp/{gtin}/{serial}/carrier/qr.png"
        try:
            r = requests.get(f"{API_URL}{path_qr}", headers=headers(token), timeout=10)
            record("carrier:qr", "GET", path_qr, r.status_code,
                   r.status_code == 200,
                   f"content-type={r.headers.get('content-type','?')}")
        except Exception as e:
            record("carrier:qr", "GET", path_qr, 0, False, str(e))


def test_compliance(token):
    print("\n  10. COMPLIANCE CHECKS")
    try:
        r = requests.get(f"{API_URL}/api/v1/compliance/status",
                         headers=headers(token), timeout=10)
        record("compliance:status", "GET", "/api/v1/compliance/status",
               r.status_code, r.status_code == 200, r.text[:80])
    except Exception as e:
        record("compliance:status", "GET", "/api/v1/compliance/status", 0, False, str(e))

    try:
        r = requests.get(f"{API_URL}/api/v1/compliance/calendar",
                         headers=headers(token), timeout=10)
        record("compliance:calendar", "GET", "/api/v1/compliance/calendar",
               r.status_code, r.status_code == 200, r.text[:80])
    except Exception as e:
        record("compliance:calendar", "GET", "/api/v1/compliance/calendar", 0, False, str(e))

    queries = load_json("demo_compliance_queries.json")
    for i, q in enumerate(queries[:2]):
        try:
            r = requests.post(
                f"{API_URL}/api/v1/compliance/check",
                headers=headers(token), json=q, timeout=30,
            )
            record(f"compliance:check:{i}", "POST", "/api/v1/compliance/check",
                   r.status_code, r.status_code == 200, r.text[:80])
        except Exception as e:
            record(f"compliance:check:{i}", "POST", "/api/v1/compliance/check", 0, False, str(e))


def test_ml_predictions(token):
    print("\n  11. ML PREDICTIONS")
    ml_inputs = load_json("demo_ml_inputs.json")
    for i, inp in enumerate(ml_inputs[:3]):
        try:
            r = requests.post(
                f"{API_URL}/api/v1/ml/predict/compliance",
                headers=headers(token), json=inp, timeout=15,
            )
            record(f"ml:predict:{i}", "POST", "/api/v1/ml/predict/compliance",
                   r.status_code, r.status_code == 200, r.text[:80])
        except Exception as e:
            record(f"ml:predict:{i}", "POST", "/api/v1/ml/predict/compliance", 0, False, str(e))

    try:
        r = requests.get(
            f"{API_URL}/api/v1/ml/predict/compliance?sector=electronics&ddp_completeness=0.85",
            headers=headers(token), timeout=15,
        )
        record("ml:predict:get", "GET", "/api/v1/ml/predict/compliance?...",
               r.status_code, r.status_code == 200, r.text[:80])
    except Exception as e:
        record("ml:predict:get", "GET", "/api/v1/ml/predict/compliance?...", 0, False, str(e))


def test_lifecycle(token):
    print("\n  12. LIFECYCLE CREATE")
    actions = load_json("demo_lifecycle_actions.json")
    for i, act in enumerate(actions[:3]):
        if act["action"] == "create":
            try:
                r = requests.post(
                    f"{API_URL}/api/v1/dpp/lifecycle/create",
                    headers=headers(token), json=act["body"], timeout=30,
                )
                record(f"lifecycle:create:{i}", "POST",
                       "/api/v1/dpp/lifecycle/create",
                       r.status_code, r.status_code in (200, 201), r.text[:80])
            except Exception as e:
                record(f"lifecycle:create:{i}", "POST",
                       "/api/v1/dpp/lifecycle/create", 0, False, str(e))


def test_audit_log(token):
    print("\n  13. AUDIT LOG")
    try:
        r = requests.get(
            f"{API_URL}/api/v1/dpp/audit-log?limit=10",
            headers=headers(token), timeout=10,
        )
        record("audit:log", "GET", "/api/v1/dpp/audit-log?limit=10",
               r.status_code, r.status_code == 200, r.text[:80])
    except Exception as e:
        record("audit:log", "GET", "/api/v1/dpp/audit-log", 0, False, str(e))


def test_human_review(token):
    print("\n  14. HUMAN REVIEW QUEUE")
    try:
        r = requests.get(
            f"{API_URL}/api/v1/human-review/pending",
            headers=headers(token), timeout=10,
        )
        record("human-review:pending", "GET", "/api/v1/human-review/pending",
               r.status_code, r.status_code == 200, r.text[:80])
    except Exception as e:
        record("human-review:pending", "GET", "/api/v1/human-review/pending", 0, False, str(e))


def test_workflow(token):
    print("\n  15. WORKFLOW RUN")
    try:
        r = requests.post(
            f"{API_URL}/api/v1/workflow/run",
            headers=headers(token),
            json={"query": "Check compliance status for electronics sector products"},
            timeout=30,
        )
        record("workflow:run", "POST", "/api/v1/workflow/run",
               r.status_code, r.status_code == 200, r.text[:80])
    except Exception as e:
        record("workflow:run", "POST", "/api/v1/workflow/run", 0, False, str(e))


def main():
    print("=" * 80)
    print("  EU DPP PLATFORM — DEMO SEED & FUNCTIONAL TEST")
    print(f"  Target: {API_URL}")
    print("=" * 80)

    # Auth
    print("\n  0. AUTHENTICATION")
    token = get_token()
    if token:
        print(f"    [PASS] Token obtained for {AUTH_USER}")
    else:
        print(f"    [WARN] No token — proceeding without auth (some endpoints may fail)")

    t0 = time.time()

    test_health(token)
    test_dpp_sectors(token)
    dpp_requests = seed_dpp_products(token)
    test_dpp_get(token, dpp_requests)
    test_dpp_list_by_sector(token)
    battery_payloads = seed_batteries(token)
    test_battery_get(token, battery_payloads)
    test_supply_chain(token, dpp_requests)
    test_qr_carrier(token, dpp_requests)
    test_compliance(token)
    test_ml_predictions(token)
    test_lifecycle(token)
    test_audit_log(token)
    test_human_review(token)
    test_workflow(token)

    elapsed = time.time() - t0

    # Report
    passed = sum(1 for r in results if r["ok"])
    failed = sum(1 for r in results if not r["ok"])

    print(f"\n{'=' * 80}")
    print(f"  TEST REPORT")
    print(f"{'=' * 80}")
    print(f"  Total tests:  {len(results)}")
    print(f"  Passed:       {passed}")
    print(f"  Failed:       {failed}")
    print(f"  Duration:     {elapsed:.1f}s")
    print(f"  Pass rate:    {passed / len(results) * 100:.1f}%")

    if failed > 0:
        print(f"\n  FAILED TESTS:")
        for r in results:
            if not r["ok"]:
                print(f"    - {r['test']}: {r['method']} {r['url']} → {r['status']} {r['detail'][:60]}")

    # Save report
    report_path = DEMO_DIR / "test_report.json"
    with open(report_path, "w") as f:
        json.dump({
            "api_url": API_URL, "total": len(results),
            "passed": passed, "failed": failed,
            "duration_s": round(elapsed, 1),
            "results": results,
        }, f, indent=2)
    print(f"\n  Report saved: {report_path}")
    print(f"{'=' * 80}\n")

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
